# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - facial-attendance

on:
  push:
    branches:
      - Palash
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install build tools for dlib
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config libx11-dev libatlas-base-dev libgtk-3-dev libboost-python-dev

      - name: Install Python3 dependencies for dlib
        run: |
          sudo apt-get install -y python3-dev python3-pip
          sudo -H pip3 install -U pip numpy

      - name: Download and compile dlib from source
        run: |
          wget http://dlib.net/files/dlib-19.24.9.tar.bz2
          tar xvf dlib-19.24.9.tar.bz2
          cd dlib-19.24.9/
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          sudo make install
          sudo ldconfig
          cd ..
          python3 setup.py install

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D082A4CAD4C4F509682CDD005D21152 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D6588A65E53A49ECA69222C476FB29EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D90BF453EE9646FA9AFABD80BEE9BF84 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'facial-attendance'
          slot-name: 'Production'
