# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - facial-attendance

on:
  push:
    branches:
      - Palash
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python3 dependencies for dlib
        run: |
          sudo apt-get install -y python3-dev python3-pip
          sudo -H pip3 install -U pip numpy

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libx11-dev libatlas-base-dev libgtk-3-dev libboost-python-dev python3-dev python3-pip
          sudo -H pip3 install -U pip numpy

      - name: Install cmake 3.29.3 and wheel==0.43.0
        run: |
          sudo apt remove --purge cmake -y
          wget https://github.com/Kitware/CMake/releases/download/v3.29.3/cmake-3.29.3-linux-x86_64.sh
          sudo mkdir /opt/cmake-3.29.3
          sudo sh cmake-3.29.3-linux-x86_64.sh --prefix=/opt/cmake-3.29.3 --skip-license
          sudo ln -sf /opt/cmake-3.29.3/bin/* /usr/local/bin/
          cmake --version  # Verify the installed version
          pip3 install wheel==0.43.0
          

      - name: Install dlib 19.24.6 using pip
        run: pip3 install dlib==19.24.6


      - name: Install Python dependencies
        run: pip3 install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D082A4CAD4C4F509682CDD005D21152 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D6588A65E53A49ECA69222C476FB29EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D90BF453EE9646FA9AFABD80BEE9BF84 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'facial-attendance'
          slot-name: 'Production'
